"""One authoring owner, a checked generated consumer for the legacy pipeline.

After an owner edit, run ``python development_environment/developer_tooling/
principles_codegen.py --write``. The autonomous loop reads the owner document
directly next turn; the legacy pipeline imports this generated consumer. CI
rejects stale generated text and a second complete literal instruction owner.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from assurance.common._console import utf8_console  # noqa: E402

utf8_console()

OWNER = ROOT / "docs" / "blueprint" / "LEGAL_BRAIN_PRINCIPLES.md"
GENERATED = ROOT / "nm/legal_brain/principles_generated.py"
HEADER = '''"""Generated legacy consumer of docs/blueprint/LEGAL_BRAIN_PRINCIPLES.md.

Do not edit this file. The document is the sole authoring owner; regeneration
and an exact-drift/duplicate-owner check live in principles_codegen.py. The
new loop loads its snapshot through PrinciplesPort at each turn boundary.
"""
'''


def rendered(text: str) -> str:
    # repr escapes any quote/newline the owner adds; never execute document text.
    chunks = [text[start : start + 12] for start in range(0, len(text), 12)] or [""]
    return (
        HEADER
        + "\nPRINCIPLES = (\n"
        + "".join("    " + repr(chunk) + "\n" for chunk in chunks)
        + ")\n"
    )


def ownership_problems(
    owner: Path = OWNER, generated: Path = GENERATED, source_root: Path = ROOT / "nm"
) -> list[str]:
    text = owner.read_text(encoding="utf-8")
    if not text.strip():
        return ["the reasoning owner is empty"]
    problems = []
    current = ast.parse(generated.read_text(encoding="utf-8"))
    value = next(
        (
            ast.literal_eval(node.value)
            for node in current.body
            if isinstance(node, ast.Assign)
            and any(
                isinstance(target, ast.Name) and target.id == "PRINCIPLES"
                for target in node.targets
            )
        ),
        None,
    )
    if value != text:
        problems.append("the generated reasoning consumer differs from its owner")
    for path in source_root.rglob("*.py"):
        if path.resolve() == generated.resolve():
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"))
        if any(
            isinstance(node, ast.Constant) and isinstance(node.value, str) and text in node.value
            for node in ast.walk(tree)
        ):
            problems.append(f"a second reasoning instruction owner exists: {path}")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    if args.write:
        GENERATED.write_text(rendered(OWNER.read_text(encoding="utf-8")), encoding="utf-8")
    problems = ownership_problems()
    print(f"principles owner: {len(problems)} problem(s)")
    for problem in problems:
        print(problem)
    return int(bool(problems))


if __name__ == "__main__":
    raise SystemExit(main())
