"""Public v3 replay generated by the exact committed parent renderer.

The isolated generator loads this application's execution_contracts.py from
105a4ff, with its exact bytes pinned below. Only its renderer and fresh receipt
version are temporarily wired during normal POST /api/turn admission/commit.
No saved row, dependency snapshot, seal or status is edited or regenerated.
Current shipped readers then reopen/replay it and admit a separate fresh v4 turn.

All model decisions are fabricated offline. This proves version handoffs and
durable mechanics, not semantic quality or real-model completion accuracy.
"""
import gzip
import hashlib
from copy import deepcopy
from pathlib import Path

from nm.brain import continuation
from nm.brain import turn as boundary
from tests.test_brain_code_acknowledgements import install, record_plan
from tests.test_brain_material import send
from tests.test_brain_pressure_release import (
    BASE_TURN,
    DATE_ID,
    NEW_DATE,
    OLD_DATE,
    OLD_RIG,
    ORIGINAL,
    date_requirement,
    initial_plan,
    reopened,
    revision,
)

PARENT_REVISION = "105a4ff"
PARENT_RENDERER_SHA256 = "4743522579b8da74e6ae39d8dba47b37b81250421cc87c0d965d1db4f32da437"


def _committed_v3_renderer():
    """Execute immutable committed parent code, never the current renderer."""
    # Frozen exact git-blob bytes also work in source exports and shallow CI
    # checkouts. The checksum rejects alteration of the historical generator.
    source = gzip.decompress((Path(__file__).parent / "fixtures" /
                              "brain_execution_renderer_v3_105a4ff.py.gz").read_bytes())
    assert hashlib.sha256(source).hexdigest() == PARENT_RENDERER_SHA256
    namespace = {"__name__": "_committed_v3_execution_contracts"}
    exec(compile(source.decode("utf-8"), "git:" + PARENT_REVISION, "exec"), namespace)
    assert namespace["RECORD_ACKNOWLEDGEMENT_CONTRACT"] == "record_acknowledgement_v3"
    return namespace["canonical_record_acknowledgements"]


def test_committed_v3_reply_reopens_replays_and_survives_fresh_v4_without_resealing(
        client, wired, monkeypatch):
    historical_turn = "parent-v3-correction"
    message = "The northern carton arrival was 19 April, correcting the earlier account."
    change = record_plan(message, candidates=[revision(NEW_DATE, message, OLD_DATE, DATE_ID)],
                         account=True)
    current_id = historical_turn + ":material:1"
    followup = "Keep the northern carton entry at its already recorded 19 April date."
    current_requirement = {**date_requirement(), "target_ids": [current_id]}
    model = install(wired, monkeypatch,
                    [initial_plan(), change,
                     record_plan(followup, requirement=current_requirement)],
                    [{}, {"status": "performed", "separate_record_status": True,
                          "expression_sources": ["L1"]},
                     {"status": "already_current", "separate_record_status": True,
                      "expression_sources": ["L1"]}])
    commits = []
    commit = wired.store.commit

    def observed_commit(matter, *, expected_version):
        commits.append((matter.version, expected_version))
        return commit(matter, expected_version=expected_version)

    monkeypatch.setattr(wired.store, "commit", observed_commit)
    old_renderer = _committed_v3_renderer()
    with monkeypatch.context() as historical:
        historical.setattr(boundary, "RECORD_ACKNOWLEDGEMENT_CONTRACT",
                           "record_acknowledgement_v3")
        historical.setattr(boundary, "canonical_record_acknowledgements", old_renderer)
        historical.setattr(continuation, "canonical_record_acknowledgements", old_renderer)
        initial = send(client, ORIGINAL, BASE_TURN)
        assert initial.status_code == 200, initial.text
        opened = initial.json()
        assert opened["metrics"]["llm_calls"] == 8
        response = send(client, message, historical_turn, opened=opened)
        assert response.status_code == 200, response.text
        historical_reply = response.json()
        assert historical_reply["metrics"]["llm_calls"] == 8

    saved = deepcopy(wired.store.load(opened["matter_id"]))
    old_row = deepcopy(saved.brain_chat[-1])
    old_execution = old_row["response"]["material_coverage"]["execution"]
    old_unit, = old_row["response"]["continuation"]["units"]
    request, = old_execution["requests"]
    assert request["acknowledgement_contract"] == "record_acknowledgement_v3"
    assert request["acknowledgement_delivery"] == "code_only"
    assert request["fulfillment"] == "fulfilled"
    assert old_execution["persistence"] == "committed"
    assert old_unit["record_outcome"]["status"] == "performed"
    assert len(old_unit["record_outcome"]["effect_ids"]) == 1
    assert old_unit["record_outcome_seal"]["receipt_id"] == old_execution["id"]
    assert old_unit["record_outcome_seal"]["resulting_version"] == saved.version
    assert [block["id"] for block in old_unit["blocks"]] == ["block:0", "record-status:0"]
    assert all(block["evidence_expression"]["operator"] == "record_result"
               for block in old_unit["blocks"])
    assert all(OLD_DATE + " → " + NEW_DATE in block["text"] for block in old_unit["blocks"])
    assert old_row["elements"] == historical_reply["elements"]
    assert old_row["response"]["elements"] == historical_reply["elements"]

    calls_before = len(model.seen)
    commits_before = len(commits)
    detail = client.get(f"/api/matters/{opened['matter_id']}")
    assert detail.status_code == 200, detail.text
    reopened_saved, active = reopened(wired, historical_reply)
    assert reopened_saved == saved and active == [OLD_RIG, NEW_DATE]
    replay = send(client, message, historical_turn, opened=opened)
    assert replay.status_code == 200, replay.text
    replayed = replay.json()
    assert replayed["replayed"] is True
    assert replayed["metrics"]["llm_calls"] == 0
    assert replayed["elements"] == historical_reply["elements"]
    assert replayed["continuation"] == historical_reply["continuation"]
    assert replayed["material_coverage"]["execution"] == old_execution
    assert len(model.seen) == calls_before and len(commits) == commits_before
    assert wired.store.load(opened["matter_id"]) == saved

    current_renderer = boundary.canonical_record_acknowledgements

    def wrongly_upgrade_saved_version(value, receipt, *, record_catalogue, replay=False):
        assert replay is True
        # Failure injection changes dispatch only. The durable row and its
        # original seals remain untouched; fresh rendering wrongly stamps v4.
        return current_renderer(value, receipt, record_catalogue=record_catalogue)

    with monkeypatch.context() as wrong_dispatch:
        wrong_dispatch.setattr(boundary, "canonical_record_acknowledgements",
                               wrongly_upgrade_saved_version)
        refused = send(client, message, historical_turn, opened=opened)
    assert refused.status_code == 409, refused.text
    assert refused.json()["detail"]["code"] == "brain_refused"
    assert "elements" not in refused.json()
    assert len(model.seen) == calls_before and len(commits) == commits_before
    assert wired.store.load(opened["matter_id"]) == saved

    current = send(client, followup, "fresh-v4-after-parent-v3", opened=opened)
    assert current.status_code == 200, current.text
    fresh_reply = current.json()
    assert fresh_reply["metrics"]["llm_calls"] == 8
    fresh_request, = fresh_reply["material_coverage"]["execution"]["requests"]
    assert fresh_request["acknowledgement_contract"] == "record_acknowledgement_v4"
    assert fresh_request["acknowledgement_delivery"] == "substantive_followup"
    assert fresh_request["fulfillment"] == "fulfilled"
    fresh_unit, = fresh_reply["continuation"]["units"]
    assert [block["evidence_expression"]["operator"] for block in fresh_unit["blocks"]] == [
        "source_account", "record_result"]
    assert fresh_unit["record_outcome"]["status"] == "already_current"
    assert fresh_unit["record_outcome"]["effect_ids"] == []
    assert fresh_unit["record_outcome"]["current_record_ids"] == [current_id]
    assert fresh_reply["material_coverage"]["execution"]["record_changes"] == []
    latest_saved, active = reopened(wired, fresh_reply)
    assert active == [OLD_RIG, NEW_DATE]
    assert len(latest_saved.brain_chat) == 3
    assert latest_saved.brain_chat[1] == old_row
    assert len(commits) == commits_before + 1

    calls_after = len(model.seen)
    commits_after = len(commits)
    old_again = send(client, message, historical_turn, opened=opened)
    assert old_again.status_code == 200, old_again.text
    assert old_again.json()["elements"] == historical_reply["elements"]
    assert old_again.json()["continuation"] == historical_reply["continuation"]
    assert old_again.json()["material_coverage"]["execution"] == old_execution
    assert old_again.json()["metrics"]["llm_calls"] == 0
    assert len(model.seen) == calls_after and len(commits) == commits_after
    assert wired.store.load(opened["matter_id"]) == latest_saved
